version: "3"
services:
  vite-react:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./my-app:/app
    command: ["sh", "-c", "npm install && npm run dev"]

volumes:
    my-app: {}